export enum GenreEnum {
  ACTION = 'ACTION',
  COMEDY = 'COMEDY',
  DRAMA = 'DRAMA',
  HORROR = 'HORROR',
  SCIFI = 'SCIFI',
  ROMANCE = 'ROMANCE',
  THRILLER = 'THRILLER',
  FANTASY = 'FANTASY',
  ANIMATION = 'ANIMATION',
  DOCUMENTARY = 'DOCUMENTARY'
}
