import { PrismaClient, AgeRating, LanguageOption } from '../generated/prisma';

const prisma = new PrismaClient();

/**
 * BATCH 3: 50 Trending Films (2019-2024)
 * Focus: Superhero, Sci-Fi, Animation, Asian Cinema, Award Winners
 */

const movieData = [
  // === SUPERHERO/COMIC 2019-2024 (12 movies) ===
  {
    title: 'Spider-Man: No Way Home',
    originalTitle: 'Spider-Man: No Way Home',
    overview: 'Peter Parker nhờ Doctor Strange giúp thế giới quên anh là Spider-Man, nhưng phép thuật sai lầm mở cổng đa vũ trụ.',
    runtime: 148,
    releaseDate: '2021-12-17',
    ageRating: AgeRating.T13,
    director: 'Jon Watts',
    cast: ['Tom Holland', 'Zendaya', 'Benedict Cumberbatch', 'Tobey Maguire'],
    genres: ['Hành động', 'Phiêu lưu', 'Khoa học viễn tưởng'],
  },
  {
    title: 'Spider-Man: Far From Home',
    originalTitle: 'Spider-Man: Far From Home',
    overview: 'Peter Parker đi du lịch châu Âu sau cái chết của Tony Stark và phải đối mặt với Mysterio.',
    runtime: 129,
    releaseDate: '2019-07-02',
    ageRating: AgeRating.T13,
    director: 'Jon Watts',
    cast: ['Tom Holland', 'Samuel L. Jackson', 'Jake Gyllenhaal', 'Zendaya'],
    genres: ['Hành động', 'Phiêu lưu', 'Khoa học viễn tưởng'],
  },
  {
    title: 'The Marvels',
    originalTitle: 'The Marvels',
    overview: 'Captain Marvel, Ms. Marvel và Monica Rambeau hoán đổi chỗ mỗi khi dùng năng lực phải hợp tác cứu vũ trụ.',
    runtime: 105,
    releaseDate: '2023-11-10',
    ageRating: AgeRating.T13,
    director: 'Nia DaCosta',
    cast: ['Brie Larson', 'Iman Vellani', 'Teyonah Parris', 'Samuel L. Jackson'],
    genres: ['Hành động', 'Phiêu lưu', 'Khoa học viễn tưởng'],
  },
  {
    title: 'Kraven the Hunter - Thợ Săn',
    originalTitle: 'Kraven the Hunter',
    overview: 'Sergei Kravinoff trở thành thợ săn siêu năng lực và đối đầu với cha ruột, trùm tội phạm Nga.',
    runtime: 127,
    releaseDate: '2024-12-13',
    ageRating: AgeRating.T18,
    director: 'J.C. Chandor',
    cast: ['Aaron Taylor-Johnson', 'Russell Crowe', 'Ariana DeBose', 'Fred Hechinger'],
    genres: ['Hành động', 'Tội phạm', 'Giật gân'],
  },
  {
    title: 'Aquaman',
    originalTitle: 'Aquaman',
    overview: 'Arthur Curry khám phá nguồn gốc Atlantis và phải ngăn chặn em trai Orm phát động chiến tranh với thế giới trên cạn.',
    runtime: 143,
    releaseDate: '2018-12-21',
    ageRating: AgeRating.T13,
    director: 'James Wan',
    cast: ['Jason Momoa', 'Amber Heard', 'Willem Dafoe', 'Patrick Wilson'],
    genres: ['Hành động', 'Phiêu lưu', 'Viễn tưởng'],
  },
  {
    title: 'Captain Marvel',
    originalTitle: 'Captain Marvel',
    overview: 'Carol Danvers - chiến binh Kree - phát hiện quá khứ thật sự và trở thành siêu anh hùng mạnh nhất vũ trụ.',
    runtime: 124,
    releaseDate: '2019-03-08',
    ageRating: AgeRating.T13,
    director: 'Anna Boden, Ryan Fleck',
    cast: ['Brie Larson', 'Samuel L. Jackson', 'Ben Mendelsohn', 'Jude Law'],
    genres: ['Hành động', 'Phiêu lưu', 'Khoa học viễn tưởng'],
  },
  {
    title: 'Black Panther',
    originalTitle: 'Black Panther',
    overview: 'T\'Challa trở về Wakanda sau cái chết của cha và phải đối mặt với Killmonger muốn chiếm ngai vàng.',
    runtime: 134,
    releaseDate: '2018-02-16',
    ageRating: AgeRating.T13,
    director: 'Ryan Coogler',
    cast: ['Chadwick Boseman', 'Michael B. Jordan', 'Lupita Nyong\'o', 'Danai Gurira'],
    genres: ['Hành động', 'Phiêu lưu', 'Khoa học viễn tưởng'],
  },
  {
    title: 'Black Widow',
    originalTitle: 'Black Widow',
    overview: 'Natasha Romanoff đối mặt với quá khứ đen tối và tổ chức Red Room đã biến cô thành sát thủ.',
    runtime: 134,
    releaseDate: '2021-07-09',
    ageRating: AgeRating.T13,
    director: 'Cate Shortland',
    cast: ['Scarlett Johansson', 'Florence Pugh', 'David Harbour', 'Rachel Weisz'],
    genres: ['Hành động', 'Phiêu lưu', 'Giật gân'],
  },
  {
    title: 'Morbius',
    originalTitle: 'Morbius',
    overview: 'Bác sĩ Michael Morbius thử nghiệm thuốc chữa bệnh máu hiếm và biến thành ma cà rồng.',
    runtime: 104,
    releaseDate: '2022-04-01',
    ageRating: AgeRating.T13,
    director: 'Daniel Espinosa',
    cast: ['Jared Leto', 'Matt Smith', 'Adria Arjona', 'Jared Harris'],
    genres: ['Hành động', 'Kinh dị', 'Khoa học viễn tưởng'],
  },
  {
    title: 'Venom',
    originalTitle: 'Venom',
    overview: 'Phóng viên Eddie Brock bị sinh vật symbiote ngoài hành tinh chiếm cơ thể và trở thành Venom.',
    runtime: 112,
    releaseDate: '2018-10-05',
    ageRating: AgeRating.T13,
    director: 'Ruben Fleischer',
    cast: ['Tom Hardy', 'Michelle Williams', 'Riz Ahmed', 'Jenny Slate'],
    genres: ['Hành động', 'Khoa học viễn tưởng'],
  },
  {
    title: 'Venom: Let There Be Carnage',
    originalTitle: 'Venom: Let There Be Carnage',
    overview: 'Eddie và Venom thích nghi với cuộc sống chung nhưng phải đối mặt với Cletus Kasady - Carnage.',
    runtime: 97,
    releaseDate: '2021-10-01',
    ageRating: AgeRating.T13,
    director: 'Andy Serkis',
    cast: ['Tom Hardy', 'Woody Harrelson', 'Michelle Williams', 'Naomie Harris'],
    genres: ['Hành động', 'Khoa học viễn tưởng'],
  },
  {
    title: 'Wonder Woman',
    originalTitle: 'Wonder Woman',
    overview: 'Diana - công chúa Amazon - rời Themyscira cùng phi công Steve Trevor để kết thúc Thế chiến I.',
    runtime: 141,
    releaseDate: '2017-06-02',
    ageRating: AgeRating.T13,
    director: 'Patty Jenkins',
    cast: ['Gal Gadot', 'Chris Pine', 'Connie Nielsen', 'Robin Wright'],
    genres: ['Hành động', 'Phiêu lưu', 'Viễn tưởng'],
  },

  // === SCI-FI/APOCALYPTIC 2019-2024 (10 movies) ===
  {
    title: 'Avatar: The Way of Water',
    originalTitle: 'Avatar: The Way of Water',
    overview: 'Jake Sully và gia đình phải rời bỏ nhà để tìm nơi ẩn náu nơi bộ tộc biển Metkayina.',
    runtime: 192,
    releaseDate: '2022-12-16',
    ageRating: AgeRating.T13,
    director: 'James Cameron',
    cast: ['Sam Worthington', 'Zoe Saldaña', 'Sigourney Weaver', 'Kate Winslet'],
    genres: ['Khoa học viễn tưởng', 'Phiêu lưu', 'Viễn tưởng'],
  },
  {
    title: 'The Creator',
    originalTitle: 'The Creator',
    overview: 'Trong tương lai, cựu quân nhân được giao nhiệm vụ săn lùng AI hàng đầu - hóa ra là đứa trẻ AI.',
    runtime: 133,
    releaseDate: '2023-09-29',
    ageRating: AgeRating.T13,
    director: 'Gareth Edwards',
    cast: ['John David Washington', 'Madeleine Yuna Voyles', 'Gemma Chan', 'Ken Watanabe'],
    genres: ['Khoa học viễn tưởng', 'Hành động', 'Giật gân'],
  },
  {
    title: 'Deja Vu - Không Gian Ảo',
    originalTitle: 'Infinite',
    overview: 'Người đàn ông bị tâm thần phân liệt phát hiện ký ức là của kiếp trước và phải ngăn chặn kẻ thù bất tử.',
    runtime: 106,
    releaseDate: '2021-06-10',
    ageRating: AgeRating.T13,
    director: 'Antoine Fuqua',
    cast: ['Mark Wahlberg', 'Chiwetel Ejiofor', 'Sophie Cookson', 'Dylan O\'Brien'],
    genres: ['Hành động', 'Khoa học viễn tưởng', 'Giật gân'],
  },
  {
    title: 'Tomorrowland - Thế Giới Bí Ẩn',
    originalTitle: 'Atlas',
    overview: 'Nhà phân tích AI chống robot phải hợp tác với AI để ngăn chặn kẻ khủng bố robot hủy diệt Trái Đất.',
    runtime: 118,
    releaseDate: '2024-05-24',
    ageRating: AgeRating.T13,
    director: 'Brad Peyton',
    cast: ['Jennifer Lopez', 'Simu Liu', 'Sterling K. Brown', 'Mark Strong'],
    genres: ['Khoa học viễn tưởng', 'Hành động'],
  },
  {
    title: 'The Tomorrow War',
    originalTitle: 'The Tomorrow War',
    overview: 'Quân đội từ tương lai tuyển dụng binh sĩ từ hiện tại để chiến đấu với người ngoài hành tinh.',
    runtime: 138,
    releaseDate: '2021-07-02',
    ageRating: AgeRating.T13,
    director: 'Chris McKay',
    cast: ['Chris Pratt', 'Yvonne Strahovski', 'J.K. Simmons', 'Betty Gilpin'],
    genres: ['Hành động', 'Khoa học viễn tưởng'],
  },
  {
    title: 'Leave the World Behind',
    originalTitle: 'Leave the World Behind',
    overview: 'Gia đình đi nghỉ mát bị mắc kẹt khi thảm họa xảy ra và chủ nhà đột ngột trở về.',
    runtime: 138,
    releaseDate: '2023-12-08',
    ageRating: AgeRating.T16,
    director: 'Sam Esmail',
    cast: ['Julia Roberts', 'Mahershala Ali', 'Ethan Hawke', 'Myha\'la'],
    genres: ['Giật gân', 'Chính kịch', 'Bí ẩn'],
  },
  {
    title: 'Reminiscence - Hồi Ức',
    originalTitle: 'Reminiscence',
    overview: 'Trong tương lai ngập lụt, đặc vụ giúp người sống lại ký ức phải điều tra sự mất tích của tình nhân.',
    runtime: 116,
    releaseDate: '2021-08-20',
    ageRating: AgeRating.T13,
    director: 'Lisa Joy',
    cast: ['Hugh Jackman', 'Rebecca Ferguson', 'Thandiwe Newton', 'Cliff Curtis'],
    genres: ['Khoa học viễn tưởng', 'Lãng mạn', 'Giật gân'],
  },
  {
    title: 'Finch',
    originalTitle: 'Finch',
    overview: 'Sau thảm họa mặt trời, kỹ sư robot tạo ra android để chăm sóc chó của mình khi ông chết.',
    runtime: 115,
    releaseDate: '2021-11-05',
    ageRating: AgeRating.T13,
    director: 'Miguel Sapochnik',
    cast: ['Tom Hanks', 'Caleb Landry Jones', 'Seamus'],
    genres: ['Khoa học viễn tưởng', 'Chính kịch', 'Phiêu lưu'],
  },
  {
    title: '65 - 65 Triệu Năm',
    originalTitle: '65',
    overview: 'Phi hành gia rơi xuống Trái Đất 65 triệu năm trước và phải sinh tồn giữa khủng long.',
    runtime: 93,
    releaseDate: '2023-03-10',
    ageRating: AgeRating.T13,
    director: 'Scott Beck, Bryan Woods',
    cast: ['Adam Driver', 'Ariana Greenblatt', 'Chloe Coleman'],
    genres: ['Khoa học viễn tưởng', 'Phiêu lưu', 'Giật gân'],
  },
  {
    title: 'Underwater - Mật Mã Biển Sâu',
    originalTitle: 'Underwater',
    overview: 'Phi hành đoàn trạm nghiên cứu dưới đáy biển phải thoát khi động đất giải phóng sinh vật bí ẩn.',
    runtime: 95,
    releaseDate: '2020-01-10',
    ageRating: AgeRating.T13,
    director: 'William Eubank',
    cast: ['Kristen Stewart', 'Vincent Cassel', 'Jessica Henwick', 'T.J. Miller'],
    genres: ['Hành động', 'Kinh dị', 'Khoa học viễn tưởng'],
  },

  // === ANIMATION 2019-2024 (10 movies) ===
  {
    title: 'Minions: The Rise of Gru',
    originalTitle: 'Minions: The Rise of Gru',
    overview: 'Gru 12 tuổi mơ ước gia nhập nhóm siêu phản diện Vicious 6 với sự giúp đỡ của Minions.',
    runtime: 87,
    releaseDate: '2022-07-01',
    ageRating: AgeRating.P,
    director: 'Kyle Balda',
    cast: ['Steve Carell', 'Pierre Coffin', 'Alan Arkin', 'Taraji P. Henson'],
    genres: ['Hoạt hình', 'Hành động', 'Hài'],
  },
  {
    title: 'Frozen II - Nữ Hoàng Băng Giá II',
    originalTitle: 'Frozen II',
    overview: 'Elsa nghe tiếng gọi bí ẩn dẫn cô và Anna đến rừng phép thuật để khám phá bí mật quá khứ.',
    runtime: 103,
    releaseDate: '2019-11-22',
    ageRating: AgeRating.P,
    director: 'Chris Buck, Jennifer Lee',
    cast: ['Idina Menzel', 'Kristen Bell', 'Josh Gad', 'Jonathan Groff'],
    genres: ['Hoạt hình', 'Phiêu lưu', 'Âm nhạc'],
  },
  {
    title: 'Soul - Cuộc Sống Nhiệm Màu',
    originalTitle: 'Soul',
    overview: 'Nhạc sĩ jazz chết trước khi thực hiện ước mơ và phải giúp linh hồn chưa sinh tìm mục đích sống.',
    runtime: 100,
    releaseDate: '2020-12-25',
    ageRating: AgeRating.P,
    director: 'Pete Docter',
    cast: ['Jamie Foxx', 'Tina Fey', 'Graham Norton', 'Rachel House'],
    genres: ['Hoạt hình', 'Gia đình', 'Âm nhạc'],
  },
  {
    title: 'Onward - Tiến Lên Phía Trước',
    originalTitle: 'Onward',
    overview: 'Hai anh em yêu tinh nhận quà phép thuật từ cha quá cố và bắt đầu hành trình hồi sinh ông.',
    runtime: 102,
    releaseDate: '2020-03-06',
    ageRating: AgeRating.P,
    director: 'Dan Scanlon',
    cast: ['Tom Holland', 'Chris Pratt', 'Julia Louis-Dreyfus', 'Octavia Spencer'],
    genres: ['Hoạt hình', 'Phiêu lưu', 'Viễn tưởng'],
  },
  {
    title: 'Raya and the Last Dragon',
    originalTitle: 'Raya and the Last Dragon',
    overview: 'Chiến binh Raya tìm rồng huyền thoại cuối cùng để cứu thế giới khỏi quái vật đen tối.',
    runtime: 107,
    releaseDate: '2021-03-05',
    ageRating: AgeRating.P,
    director: 'Don Hall, Carlos López Estrada',
    cast: ['Kelly Marie Tran', 'Awkwafina', 'Gemma Chan', 'Daniel Dae Kim'],
    genres: ['Hoạt hình', 'Phiêu lưu', 'Viễn tưởng'],
  },
  {
    title: 'Migration - Cuộc Di Cư',
    originalTitle: 'Migration',
    overview: 'Gia đình vịt Mallard rời ao nhà để di cư đến Jamaica và gặp nhiều rắc rối dọc đường.',
    runtime: 83,
    releaseDate: '2023-12-22',
    ageRating: AgeRating.P,
    director: 'Benjamin Renner',
    cast: ['Kumail Nanjiani', 'Elizabeth Banks', 'Keegan-Michael Key', 'Awkwafina'],
    genres: ['Hoạt hình', 'Gia đình', 'Phiêu lưu'],
  },
  {
    title: 'Leo',
    originalTitle: 'Leo',
    overview: 'Con thằn lằn già 74 tuổi ở lớp học quyết định trốn thoát nhưng bị học sinh mang về nhà.',
    runtime: 102,
    releaseDate: '2023-11-21',
    ageRating: AgeRating.P,
    director: 'Robert Marianetti, Robert Smigel, David Wachtenheim',
    cast: ['Adam Sandler', 'Bill Burr', 'Cecily Strong', 'Jason Alexander'],
    genres: ['Hoạt hình', 'Gia đình', 'Hài'],
  },
  {
    title: 'Trolls Band Together',
    originalTitle: 'Trolls Band Together',
    overview: 'Poppy và Branch khám phá Branch từng là thành viên nhóm nhạc BroZone và phải cứu anh trai bị bắt.',
    runtime: 91,
    releaseDate: '2023-11-17',
    ageRating: AgeRating.P,
    director: 'Walt Dohrn',
    cast: ['Anna Kendrick', 'Justin Timberlake', 'Eric André', 'Kid Cudi'],
    genres: ['Hoạt hình', 'Gia đình', 'Âm nhạc'],
  },
  {
    title: 'Toy Story 4',
    originalTitle: 'Toy Story 4',
    overview: 'Woody và băng đồ chơi cùng Bonnie đi du lịch và gặp lại Bo Peep, phải quyết định về tương lai.',
    runtime: 100,
    releaseDate: '2019-06-21',
    ageRating: AgeRating.P,
    director: 'Josh Cooley',
    cast: ['Tom Hanks', 'Tim Allen', 'Annie Potts', 'Tony Hale'],
    genres: ['Hoạt hình', 'Phiêu lưu', 'Gia đình'],
  },
  {
    title: 'How to Train Your Dragon: The Hidden World',
    originalTitle: 'How to Train Your Dragon: The Hidden World',
    overview: 'Hiccup và Toothless phát hiện thế giới rồng ẩn giấu và phải đối mặt với thợ săn rồng mới.',
    runtime: 104,
    releaseDate: '2019-02-22',
    ageRating: AgeRating.P,
    director: 'Dean DeBlois',
    cast: ['Jay Baruchel', 'America Ferrera', 'Cate Blanchett', 'F. Murray Abraham'],
    genres: ['Hoạt hình', 'Phiêu lưu', 'Viễn tưởng'],
  },

  // === ASIAN CINEMA 2019-2024 (8 movies) ===
  {
    title: 'Train to Busan',
    originalTitle: 'Busanhaeng',
    overview: 'Hành khách trên tàu cao tốc đến Busan phải sinh tồn khi đại dịch zombie bùng phát trên tàu.',
    runtime: 118,
    releaseDate: '2016-07-20',
    ageRating: AgeRating.T16,
    director: 'Yeon Sang-ho',
    cast: ['Gong Yoo', 'Ma Dong-seok', 'Jung Yu-mi', 'Kim Su-an'],
    genres: ['Hành động', 'Kinh dị', 'Giật gân'],
  },
  {
    title: 'Parasite - Ký Sinh Trùng',
    originalTitle: 'Gisaengchung',
    overview: 'Gia đình nghèo dần xâm nhập vào cuộc sống của gia đình giàu có, dẫn đến hậu quả khủng khiếp.',
    runtime: 132,
    releaseDate: '2019-05-30',
    ageRating: AgeRating.T16,
    director: 'Bong Joon-ho',
    cast: ['Song Kang-ho', 'Lee Sun-kyun', 'Cho Yeo-jeong', 'Choi Woo-shik'],
    genres: ['Giật gân', 'Chính kịch', 'Hài'],
  },
  {
    title: 'Suzume - Suzume no Tojimari',
    originalTitle: 'Suzume no Tojimari',
    overview: 'Cô gái gặp thanh niên bí ẩn và cùng nhau đóng cánh cửa dẫn đến thảm họa khắp Nhật Bản.',
    runtime: 122,
    releaseDate: '2022-11-11',
    ageRating: AgeRating.P,
    director: 'Makoto Shinkai',
    cast: ['Nanoka Hara', 'Hokuto Matsumura', 'Eri Fukatsu'],
    genres: ['Hoạt hình', 'Viễn tưởng', 'Phiêu lưu'],
  },
  {
    title: 'Battle: Los Angeles',
    originalTitle: 'The Roundup',
    overview: 'Thám tử Ma Dong-seok đuổi theo tên sát nhân nghiền tạng từ Hàn Quốc đến Việt Nam.',
    runtime: 106,
    releaseDate: '2022-05-18',
    ageRating: AgeRating.T18,
    director: 'Lee Sang-yong',
    cast: ['Ma Dong-seok', 'Son Suk-ku', 'Choi Guy-hwa'],
    genres: ['Hành động', 'Tội phạm'],
  },
  {
    title: 'Smugglers - Buôn Lậu',
    originalTitle: 'Milsu',
    overview: 'Thập niên 70, nhóm phụ nữ làng chài bị lôi kéo vào đường dây buôn lậu nguy hiểm.',
    runtime: 129,
    releaseDate: '2023-07-26',
    ageRating: AgeRating.T16,
    director: 'Ryoo Seung-wan',
    cast: ['Kim Hye-soo', 'Yum Jung-ah', 'Jo In-sung', 'Park Jeong-min'],
    genres: ['Hành động', 'Tội phạm', 'Chính kịch'],
  },
  {
    title: 'The Boy and the Heron',
    originalTitle: 'Kimitachi wa Dō Ikiru ka',
    overview: 'Cậu bé mất mẹ trong chiến tranh đi theo con diệc bí ẩn vào thế giới kỳ lạ tìm kiếm sự thật.',
    runtime: 124,
    releaseDate: '2023-07-14',
    ageRating: AgeRating.T13,
    director: 'Hayao Miyazaki',
    cast: ['Soma Santoki', 'Masaki Suda', 'Takuya Kimura', 'Aimyon'],
    genres: ['Hoạt hình', 'Viễn tưởng', 'Chính kịch'],
  },
  {
    title: 'Demon Slayer: Mugen Train',
    originalTitle: 'Kimetsu no Yaiba: Mugen Ressha-hen',
    overview: 'Tanjiro và nhóm lên tàu Mugen để điều tra sự mất tích bí ẩn của hành khách.',
    runtime: 117,
    releaseDate: '2020-10-16',
    ageRating: AgeRating.T16,
    director: 'Haruo Sotozaki',
    cast: ['Natsuki Hanae', 'Akari Kitō', 'Hiro Shimono', 'Yoshitsugu Matsuoka'],
    genres: ['Hoạt hình', 'Hành động', 'Viễn tưởng'],
  },
  {
    title: 'Jujutsu Kaisen 0',
    originalTitle: 'Jujutsu Kaisen 0',
    overview: 'Yuta Okkotsu bị lời nguyền của bạn gái đã mất ám và được đưa đến trường Jujutsu.',
    runtime: 105,
    releaseDate: '2021-12-24',
    ageRating: AgeRating.T16,
    director: 'Sunghoo Park',
    cast: ['Megumi Ogata', 'Kana Hanazawa', 'Yuichi Nakamura'],
    genres: ['Hoạt hình', 'Hành động', 'Viễn tưởng'],
  },

  // === AWARD WINNERS 2019-2024 (10 movies) ===
  {
    title: 'The Father',
    originalTitle: 'The Father',
    overview: 'Người đàn ông 80 tuổi mắc chứng mất trí nhớ phải đối mặt với thực tại đang thay đổi liên tục.',
    runtime: 97,
    releaseDate: '2020-12-11',
    ageRating: AgeRating.T13,
    director: 'Florian Zeller',
    cast: ['Anthony Hopkins', 'Olivia Colman', 'Mark Gatiss', 'Imogen Poots'],
    genres: ['Chính kịch'],
  },
  {
    title: 'Marriage Story',
    originalTitle: 'Marriage Story',
    overview: 'Đôi vợ chồng diễn viên và đạo diễn ly hôn và đấu tranh quyền nuôi con qua hệ thống pháp lý.',
    runtime: 137,
    releaseDate: '2019-11-06',
    ageRating: AgeRating.T16,
    director: 'Noah Baumbach',
    cast: ['Adam Driver', 'Scarlett Johansson', 'Laura Dern', 'Ray Liotta'],
    genres: ['Chính kịch', 'Lãng mạn'],
  },
  {
    title: 'Manchester by the Sea',
    originalTitle: 'Manchester by the Sea',
    overview: 'Người đàn ông trở về quê hương chăm cháu sau cái chết của anh trai và đối mặt với bi kịch quá khứ.',
    runtime: 137,
    releaseDate: '2016-11-18',
    ageRating: AgeRating.T16,
    director: 'Kenneth Lonergan',
    cast: ['Casey Affleck', 'Michelle Williams', 'Lucas Hedges', 'Kyle Chandler'],
    genres: ['Chính kịch'],
  },
  {
    title: 'Moonlight - Ánh Trăng',
    originalTitle: 'Moonlight',
    overview: 'Cuộc đời thanh niên da đen nghèo khó ở Miami qua ba giai đoạn, đối mặt với bản dạng và tình yêu.',
    runtime: 111,
    releaseDate: '2016-10-21',
    ageRating: AgeRating.T16,
    director: 'Barry Jenkins',
    cast: ['Trevante Rhodes', 'André Holland', 'Janelle Monáe', 'Ashton Sanders'],
    genres: ['Chính kịch'],
  },
  {
    title: 'Room - Căn Phòng',
    originalTitle: 'Room',
    overview: 'Người mẹ trẻ và con trai 5 tuổi thoát khỏi căn phòng nơi họ bị giam cầm và thích nghi với thế giới ngoài.',
    runtime: 118,
    releaseDate: '2015-10-16',
    ageRating: AgeRating.T16,
    director: 'Lenny Abrahamson',
    cast: ['Brie Larson', 'Jacob Tremblay', 'Sean Bridgers', 'Joan Allen'],
    genres: ['Chính kịch', 'Giật gân'],
  },
  {
    title: 'Spotlight - Tiêu Điểm',
    originalTitle: 'Spotlight',
    overview: 'Đội phóng viên Boston Globe điều tra vụ bê bối lạm dụng tình dục trong Giáo hội Công giáo.',
    runtime: 129,
    releaseDate: '2015-11-06',
    ageRating: AgeRating.T16,
    director: 'Tom McCarthy',
    cast: ['Michael Keaton', 'Mark Ruffalo', 'Rachel McAdams', 'Stanley Tucci'],
    genres: ['Chính kịch', 'Tiểu sử', 'Lịch sử'],
  },
  {
    title: 'The Favorite - Cuộc Đấu Yêu',
    originalTitle: 'The Favourite',
    overview: 'Hai phụ nữ cạnh tranh để trở thành người thân cận nhất của Nữ hoàng Anne nước Anh thế kỷ 18.',
    runtime: 119,
    releaseDate: '2018-11-23',
    ageRating: AgeRating.T16,
    director: 'Yorgos Lanthimos',
    cast: ['Olivia Colman', 'Emma Stone', 'Rachel Weisz', 'Nicholas Hoult'],
    genres: ['Chính kịch', 'Hài', 'Lịch sử'],
  },
  {
    title: 'Birdman - Người Chim',
    originalTitle: 'Birdman',
    overview: 'Diễn viên nổi tiếng một thời với vai siêu anh hùng cố gắng tái sinh sự nghiệp với vở kịch Broadway.',
    runtime: 119,
    releaseDate: '2014-10-17',
    ageRating: AgeRating.T16,
    director: 'Alejandro González Iñárritu',
    cast: ['Michael Keaton', 'Emma Stone', 'Edward Norton', 'Naomi Watts'],
    genres: ['Chính kịch', 'Hài'],
  },
  {
    title: 'The Grand Budapest Hotel',
    originalTitle: 'The Grand Budapest Hotel',
    overview: 'Câu chuyện về người quản lý khách sạn huyền thoại và cậu nhân viên bị cuốn vào vụ đánh cắp tranh.',
    runtime: 99,
    releaseDate: '2014-03-28',
    ageRating: AgeRating.T13,
    director: 'Wes Anderson',
    cast: ['Ralph Fiennes', 'Tony Revolori', 'Saoirse Ronan', 'Willem Dafoe'],
    genres: ['Hài', 'Chính kịch', 'Phiêu lưu'],
  },
  {
    title: 'Lady Bird',
    originalTitle: 'Lady Bird',
    overview: 'Cô gái tuổi teen ở Sacramento mơ ước đến đại học Bờ Đông và đấu tranh với mẹ.',
    runtime: 94,
    releaseDate: '2017-11-03',
    ageRating: AgeRating.T16,
    director: 'Greta Gerwig',
    cast: ['Saoirse Ronan', 'Laurie Metcalf', 'Tracy Letts', 'Timothée Chalamet'],
    genres: ['Chính kịch', 'Hài'],
  },
];

async function main() {
  console.log('🌱 Seeding Movie Service database - BATCH 3 (50 trending 2019-2024)...\n');
  console.log('⚠️ Skipping existing movies by originalTitle...\n');

  const existingGenres = await prisma.genre.findMany();
  const genreMap = new Map(existingGenres.map(g => [g.name, g.id]));

  let successCount = 0;
  let skippedCount = 0;
  let errorCount = 0;

  for (let i = 0; i < movieData.length; i++) {
    const movie = movieData[i];
    try {
      const exists = await prisma.movie.findFirst({
        where: { originalTitle: movie.originalTitle }
      });

      if (exists) {
        skippedCount++;
        console.log(`⏭️  [${i + 1}/${movieData.length}] Skipped (exists): ${movie.title}`);
        continue;
      }

      const createdMovie = await prisma.movie.create({
        data: {
          title: movie.title,
          originalTitle: movie.originalTitle,
          overview: movie.overview,
          posterUrl: `https://via.placeholder.com/500x750?text=${encodeURIComponent(movie.title.slice(0, 20))}`,
          trailerUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
          backdropUrl: `https://via.placeholder.com/1920x1080?text=${encodeURIComponent(movie.title.slice(0, 20))}`,
          runtime: movie.runtime,
          releaseDate: new Date(movie.releaseDate),
          ageRating: movie.ageRating,
          originalLanguage: 'en',
          spokenLanguages: ['vi', 'en'],
          productionCountry: 'Hoa Kỳ',
          languageType: LanguageOption.SUBTITLE,
          director: movie.director,
          cast: movie.cast,
        },
      });

      for (const genreName of movie.genres) {
        const genreId = genreMap.get(genreName);
        if (genreId) {
          await prisma.movieGenre.create({
            data: { movieId: createdMovie.id, genreId },
          });
        }
      }

      successCount++;
      console.log(`✅ [${i + 1}/${movieData.length}] ${movie.title}`);
    } catch (error) {
      errorCount++;
      console.error(`❌ [${i + 1}/${movieData.length}] Failed: ${movie.title}`, error);
    }
  }

  console.log(`\n🎉 Batch 3 complete: ${successCount} created, ${skippedCount} skipped, ${errorCount} failed`);
}

main()
  .catch((e) => {
    console.error('❌ Error seeding database:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
