import { PrismaClient, AgeRating, LanguageOption } from '../generated/prisma';

const prisma = new PrismaClient();

/**
 * BATCH 2: 50 Trending Films (2018-2025)
 * Focus: Action/Thriller, Comedy, Horror, Romantic Drama, Sci-Fi
 */

const movieData = [
  // === ACTION/THRILLER 2018-2025 (15 movies) ===
  {
    title: 'John Wick: Chapter 4',
    originalTitle: 'John Wick: Chapter 4',
    overview: 'John Wick phải đối đầu với Bàn Tròn và tìm cách giành tự do bằng cách thách đấu với Marquis de Gramont.',
    runtime: 169,
    releaseDate: '2023-03-24',
    ageRating: AgeRating.T18,
    director: 'Chad Stahelski',
    cast: ['Keanu Reeves', 'Donnie Yen', 'Bill Skarsgård', 'Laurence Fishburne'],
    genres: ['Hành động', 'Tội phạm', 'Giật gân'],
  },
  {
    title: 'The Beekeeper - Thợ Nuôi Ong',
    originalTitle: 'The Beekeeper',
    overview: 'Cựu đặc vụ bí mật trả thù tổ chức lừa đảo đã khiến hàng xóm yêu quý của anh tự tử.',
    runtime: 105,
    releaseDate: '2024-01-12',
    ageRating: AgeRating.T18,
    director: 'David Ayer',
    cast: ['Jason Statham', 'Emmy Raver-Lampman', 'Josh Hutcherson', 'Jeremy Irons'],
    genres: ['Hành động', 'Giật gân'],
  },
  {
    title: 'The Fall Guy - Người Đóng Thế',
    originalTitle: 'The Fall Guy',
    overview: 'Người đóng thế phải tìm ngôi sao điện ảnh mất tích trong khi cố gắng giành lại tình cũ là đạo diễn.',
    runtime: 126,
    releaseDate: '2024-05-03',
    ageRating: AgeRating.T13,
    director: 'David Leitch',
    cast: ['Ryan Gosling', 'Emily Blunt', 'Aaron Taylor-Johnson', 'Hannah Waddingham'],
    genres: ['Hành động', 'Hài hước', 'Lãng mạn'],
  },
  {
    title: 'Bad Boys: Ride or Die',
    originalTitle: 'Bad Boys: Ride or Die',
    overview: 'Mike và Marcus phải chạy trốn khi bị vu oan và chứng minh Captain Howard vô tội.',
    runtime: 115,
    releaseDate: '2024-06-07',
    ageRating: AgeRating.T16,
    director: 'Adil El Arbi, Bilall Fallah',
    cast: ['Will Smith', 'Martin Lawrence', 'Vanessa Hudgens', 'Alexander Ludwig'],
    genres: ['Hành động', 'Hài hước', 'Tội phạm'],
  },
  {
    title: 'Godzilla x Kong: The New Empire',
    originalTitle: 'Godzilla x Kong: The New Empire',
    overview: 'Kong và Godzilla phải hợp tác chống lại mối đe dọa mới từ thế giới rỗng bên dưới Trái Đất.',
    runtime: 115,
    releaseDate: '2024-03-29',
    ageRating: AgeRating.T13,
    director: 'Adam Wingard',
    cast: ['Rebecca Hall', 'Brian Tyree Henry', 'Dan Stevens', 'Kaylee Hottle'],
    genres: ['Hành động', 'Khoa học viễn tưởng', 'Quái vật'],
  },
  {
    title: 'Kingdom of the Planet of the Apes',
    originalTitle: 'Kingdom of the Planet of the Apes',
    overview: 'Nhiều thế hệ sau Caesar, một con vượn trẻ bắt đầu hành trình định hình tương lai của cả vượn và con người.',
    runtime: 145,
    releaseDate: '2024-05-10',
    ageRating: AgeRating.T13,
    director: 'Wes Ball',
    cast: ['Owen Teague', 'Freya Allan', 'Kevin Durand', 'Peter Macon'],
    genres: ['Khoa học viễn tưởng', 'Hành động', 'Phiêu lưu'],
  },
  {
    title: 'Deadpool & Wolverine',
    originalTitle: 'Deadpool & Wolverine',
    overview: 'Deadpool bị TVA bắt và phải hợp tác với Wolverine để cứu đa vũ trụ.',
    runtime: 127,
    releaseDate: '2024-07-26',
    ageRating: AgeRating.T18,
    director: 'Shawn Levy',
    cast: ['Ryan Reynolds', 'Hugh Jackman', 'Emma Corrin', 'Matthew Macfadyen'],
    genres: ['Hành động', 'Hài hước', 'Siêu anh hùng'],
  },
  {
    title: 'Twisters',
    originalTitle: 'Twisters',
    overview: 'Nhà khí tượng học bị ám ảnh bởi bão trở lại Oklahoma để thử nghiệm hệ thống cảnh báo mới.',
    runtime: 122,
    releaseDate: '2024-07-19',
    ageRating: AgeRating.T13,
    director: 'Lee Isaac Chung',
    cast: ['Daisy Edgar-Jones', 'Glen Powell', 'Anthony Ramos', 'Brandon Perea'],
    genres: ['Hành động', 'Thảm họa', 'Phiêu lưu'],
  },
  {
    title: 'The Killer - Kẻ Sát Nhân',
    originalTitle: 'The Killer',
    overview: 'Sát thủ chuyên nghiệp bắt đầu khủng hoảng tâm lý sau nhiệm vụ thất bại và phải trả thù.',
    runtime: 118,
    releaseDate: '2023-11-10',
    ageRating: AgeRating.T18,
    director: 'David Fincher',
    cast: ['Michael Fassbender', 'Tilda Swinton', 'Charles Parnell', 'Arliss Howard'],
    genres: ['Hành động', 'Giật gân', 'Tội phạm'],
  },
  {
    title: 'Napoleon',
    originalTitle: 'Napoleon',
    overview: 'Câu chuyện về Napoleon Bonaparte từ sĩ quan pháo binh đến Hoàng đế Pháp.',
    runtime: 158,
    releaseDate: '2023-11-22',
    ageRating: AgeRating.T16,
    director: 'Ridley Scott',
    cast: ['Joaquin Phoenix', 'Vanessa Kirby', 'Tahar Rahim', 'Rupert Everett'],
    genres: ['Chính kịch', 'Lịch sử', 'Chiến tranh'],
  },
  {
    title: 'Argylle',
    originalTitle: 'Argylle',
    overview: 'Nhà văn tiểu thuyết gián điệp phát hiện câu chuyện của mình trùng khớp với hoạt động thực của tổ chức bí mật.',
    runtime: 139,
    releaseDate: '2024-02-02',
    ageRating: AgeRating.T13,
    director: 'Matthew Vaughn',
    cast: ['Bryce Dallas Howard', 'Sam Rockwell', 'Henry Cavill', 'Dua Lipa'],
    genres: ['Hành động', 'Hài hước', 'Gián điệp'],
  },
  {
    title: 'Borderlands',
    originalTitle: 'Borderlands',
    overview: 'Nhóm săn tiền thưởng đến hành tinh Pandora để tìm con gái của Atlas và khám phá bí mật cổ đại.',
    runtime: 102,
    releaseDate: '2024-08-09',
    ageRating: AgeRating.T13,
    director: 'Eli Roth',
    cast: ['Cate Blanchett', 'Kevin Hart', 'Jack Black', 'Jamie Lee Curtis'],
    genres: ['Hành động', 'Khoa học viễn tưởng', 'Hài hước'],
  },
  {
    title: 'Lift - Phi Vụ Trên Mây',
    originalTitle: 'Lift',
    overview: 'Nhóm trộm chuyên nghiệp được tuyển dụng để đánh cắp 500 triệu đô la vàng trên máy bay.',
    runtime: 107,
    releaseDate: '2024-01-12',
    ageRating: AgeRating.T13,
    director: 'F. Gary Gray',
    cast: ['Kevin Hart', 'Gugu Mbatha-Raw', 'Sam Worthington', 'Vincent D\'Onofrio'],
    genres: ['Hành động', 'Hài hước', 'Tội phạm'],
  },
  {
    title: 'Road House',
    originalTitle: 'Road House',
    overview: 'Võ sĩ MMA cũ nhận công việc bảo vệ quán bar ở Florida Keys và đối mặt với băng đảng địa phương.',
    runtime: 121,
    releaseDate: '2024-03-21',
    ageRating: AgeRating.T16,
    director: 'Doug Liman',
    cast: ['Jake Gyllenhaal', 'Daniela Melchior', 'Conor McGregor', 'Billy Magnussen'],
    genres: ['Hành động', 'Giật gân'],
  },
  {
    title: 'Madame Web',
    originalTitle: 'Madame Web',
    overview: 'Nhân viên cấp cứu phát hiện khả năng nhìn thấy tương lai và phải bảo vệ ba cô gái khỏi sát thủ.',
    runtime: 116,
    releaseDate: '2024-02-14',
    ageRating: AgeRating.T13,
    director: 'S.J. Clarkson',
    cast: ['Dakota Johnson', 'Sydney Sweeney', 'Isabela Merced', 'Celeste O\'Connor'],
    genres: ['Hành động', 'Siêu anh hùng', 'Giật gân'],
  },

  // === COMEDY 2018-2025 (10 movies) ===
  {
    title: 'Anyone But You',
    originalTitle: 'Anyone But You',
    overview: 'Hai người ghét nhau sau buổi hẹn đầu thất bại phải giả vờ yêu nhau tại đám cưới ở Úc.',
    runtime: 103,
    releaseDate: '2023-12-22',
    ageRating: AgeRating.T16,
    director: 'Will Gluck',
    cast: ['Sydney Sweeney', 'Glen Powell', 'Alexandra Shipp', 'GaTa'],
    genres: ['Hài hước', 'Lãng mạn'],
  },
  {
    title: 'The Idea of You',
    originalTitle: 'The Idea of You',
    overview: 'Người mẹ đơn thân 40 tuổi yêu ngôi sao nhạc pop 24 tuổi sau cuộc gặp tại lễ hội âm nhạc.',
    runtime: 115,
    releaseDate: '2024-05-02',
    ageRating: AgeRating.T16,
    director: 'Michael Showalter',
    cast: ['Anne Hathaway', 'Nicholas Galitzine', 'Ella Rubin', 'Annie Mumolo'],
    genres: ['Lãng mạn', 'Hài hước', 'Chính kịch'],
  },
  {
    title: 'Hit Man',
    originalTitle: 'Hit Man',
    overview: 'Giáo viên tâm lý giả làm sát thủ cho cảnh sát và yêu một phụ nữ muốn thuê anh giết chồng.',
    runtime: 113,
    releaseDate: '2024-06-07',
    ageRating: AgeRating.T16,
    director: 'Richard Linklater',
    cast: ['Glen Powell', 'Adria Arjona', 'Austin Amelio', 'Retta'],
    genres: ['Hài hước', 'Tội phạm', 'Lãng mạn'],
  },
  {
    title: 'Fly Me to the Moon',
    originalTitle: 'Fly Me to the Moon',
    overview: 'Chuyên gia marketing được thuê để quảng bá Apollo 11 và được lệnh làm giả video đổ bộ mặt trăng.',
    runtime: 132,
    releaseDate: '2024-07-12',
    ageRating: AgeRating.T13,
    director: 'Greg Berlanti',
    cast: ['Scarlett Johansson', 'Channing Tatum', 'Woody Harrelson', 'Ray Romano'],
    genres: ['Hài hước', 'Lãng mạn', 'Lịch sử'],
  },
  {
    title: 'Challengers - Tình Địch',
    originalTitle: 'Challengers',
    overview: 'Cựu thần đồng tennis bị kẹt giữa hai người đàn ông từng là bạn thân, giờ là đối thủ.',
    runtime: 131,
    releaseDate: '2024-04-26',
    ageRating: AgeRating.T16,
    director: 'Luca Guadagnino',
    cast: ['Zendaya', 'Josh O\'Connor', 'Mike Faist'],
    genres: ['Chính kịch', 'Lãng mạn', 'Thể thao'],
  },
  {
    title: 'Mean Girls (2024)',
    originalTitle: 'Mean Girls',
    overview: 'Cô gái mới chuyển đến được nhóm nổi tiếng nhất trường nhận vào và bị cuốn vào thế giới teen drama.',
    runtime: 112,
    releaseDate: '2024-01-12',
    ageRating: AgeRating.T13,
    director: 'Samantha Jayne, Arturo Perez Jr.',
    cast: ['Angourie Rice', 'Reneé Rapp', 'Auli\'i Cravalho', 'Jaquel Spivey'],
    genres: ['Hài hước', 'Nhạc kịch', 'Tuổi teen'],
  },
  {
    title: 'Ghostbusters: Frozen Empire',
    originalTitle: 'Ghostbusters: Frozen Empire',
    overview: 'Gia đình Spengler đối mặt với thực thể cổ đại có thể đóng băng cả thành phố New York.',
    runtime: 115,
    releaseDate: '2024-03-22',
    ageRating: AgeRating.T13,
    director: 'Gil Kenan',
    cast: ['Mckenna Grace', 'Paul Rudd', 'Carrie Coon', 'Finn Wolfhard'],
    genres: ['Hài hước', 'Kỳ ảo', 'Phiêu lưu'],
  },
  {
    title: 'Wonka',
    originalTitle: 'Wonka',
    overview: 'Câu chuyện về Willy Wonka trẻ tuổi và hành trình trở thành nhà làm kẹo vĩ đại nhất thế giới.',
    runtime: 116,
    releaseDate: '2023-12-15',
    ageRating: AgeRating.P,
    director: 'Paul King',
    cast: ['Timothée Chalamet', 'Calah Lane', 'Keegan-Michael Key', 'Olivia Colman'],
    genres: ['Gia đình', 'Kỳ ảo', 'Nhạc kịch'],
  },
  {
    title: 'Bob Marley: One Love',
    originalTitle: 'Bob Marley: One Love',
    overview: 'Câu chuyện về Bob Marley vượt qua vụ ám sát và tạo ra album huyền thoại Exodus.',
    runtime: 107,
    releaseDate: '2024-02-14',
    ageRating: AgeRating.T13,
    director: 'Reinaldo Marcus Green',
    cast: ['Kingsley Ben-Adir', 'Lashana Lynch', 'James Norton'],
    genres: ['Tiểu sử', 'Âm nhạc', 'Chính kịch'],
  },
  {
    title: 'IF - Bạn Tưởng Tượng',
    originalTitle: 'IF',
    overview: 'Cô bé có khả năng nhìn thấy bạn tưởng tượng bị bỏ rơi giúp chúng tìm chủ nhân mới.',
    runtime: 104,
    releaseDate: '2024-05-17',
    ageRating: AgeRating.P,
    director: 'John Krasinski',
    cast: ['Ryan Reynolds', 'John Krasinski', 'Cailey Fleming', 'Fiona Shaw'],
    genres: ['Gia đình', 'Kỳ ảo', 'Hài hước'],
  },

  // === HORROR 2018-2025 (10 movies) ===
  {
    title: 'Longlegs - Sát Nhân Giấu Mặt',
    originalTitle: 'Longlegs',
    overview: 'Đặc vụ FBI trẻ được giao điều tra vụ án kẻ giết người hàng loạt bí ẩn có liên hệ với quỷ dữ.',
    runtime: 101,
    releaseDate: '2024-07-12',
    ageRating: AgeRating.T18,
    director: 'Oz Perkins',
    cast: ['Maika Monroe', 'Nicolas Cage', 'Blair Underwood', 'Alicia Witt'],
    genres: ['Kinh dị', 'Giật gân', 'Tội phạm'],
  },
  {
    title: 'A Quiet Place: Day One',
    originalTitle: 'A Quiet Place: Day One',
    overview: 'Câu chuyện về ngày đầu tiên quái vật xâm chiếm New York và một phụ nữ ung thư phải sinh tồn.',
    runtime: 99,
    releaseDate: '2024-06-28',
    ageRating: AgeRating.T13,
    director: 'Michael Sarnoski',
    cast: ['Lupita Nyong\'o', 'Joseph Quinn', 'Alex Wolff', 'Djimon Hounsou'],
    genres: ['Kinh dị', 'Khoa học viễn tưởng', 'Giật gân'],
  },
  {
    title: 'The First Omen',
    originalTitle: 'The First Omen',
    overview: 'Nữ tu trẻ đến Rome và phát hiện âm mưu đen tối để đưa Antichrist vào thế giới.',
    runtime: 120,
    releaseDate: '2024-04-05',
    ageRating: AgeRating.T18,
    director: 'Arkasha Stevenson',
    cast: ['Nell Tiger Free', 'Ralph Ineson', 'Sonia Braga', 'Bill Nighy'],
    genres: ['Kinh dị', 'Siêu nhiên', 'Giật gân'],
  },
  {
    title: 'Abigail',
    originalTitle: 'Abigail',
    overview: 'Nhóm bắt cóc phát hiện con gái của trùm tội phạm mà họ bắt cóc thực ra là ma cà rồng.',
    runtime: 109,
    releaseDate: '2024-04-19',
    ageRating: AgeRating.T18,
    director: 'Matt Bettinelli-Olpin, Tyler Gillett',
    cast: ['Melissa Barrera', 'Dan Stevens', 'Alisha Weir', 'Kathryn Newton'],
    genres: ['Kinh dị', 'Hành động', 'Hài hước đen'],
  },
  {
    title: 'Immaculate - Vô Nhiễm',
    originalTitle: 'Immaculate',
    overview: 'Nữ tu Mỹ đến tu viện Ý và phát hiện mình mang thai dù còn trinh, hé lộ bí mật rùng rợn.',
    runtime: 89,
    releaseDate: '2024-03-22',
    ageRating: AgeRating.T18,
    director: 'Michael Mohan',
    cast: ['Sydney Sweeney', 'Álvaro Morte', 'Benedetta Porcaroli', 'Dora Romano'],
    genres: ['Kinh dị', 'Giật gân'],
  },
  {
    title: 'Late Night with the Devil',
    originalTitle: 'Late Night with the Devil',
    overview: 'Năm 1977, talk show truyền hình trực tiếp mời cô gái bị quỷ ám và mọi thứ vượt tầm kiểm soát.',
    runtime: 93,
    releaseDate: '2024-03-22',
    ageRating: AgeRating.T18,
    director: 'Colin Cairnes, Cameron Cairnes',
    cast: ['David Dastmalchian', 'Laura Gordon', 'Ian Bliss', 'Fayssal Bazzi'],
    genres: ['Kinh dị', 'Siêu nhiên', 'Giật gân'],
  },
  {
    title: 'The Watchers',
    originalTitle: 'The Watchers',
    overview: 'Nữ nghệ sĩ mắc kẹt trong rừng Ireland với nhóm người bị sinh vật bí ẩn theo dõi mỗi đêm.',
    runtime: 102,
    releaseDate: '2024-06-07',
    ageRating: AgeRating.T13,
    director: 'Ishana Shyamalan',
    cast: ['Dakota Fanning', 'Georgina Campbell', 'Olwen Fouéré', 'Oliver Finnegan'],
    genres: ['Kinh dị', 'Kỳ ảo', 'Bí ẩn'],
  },
  {
    title: 'Trap - Bẫy',
    originalTitle: 'Trap',
    overview: 'Người cha đưa con gái đến concert và phát hiện cảnh sát đang săn kẻ giết người hàng loạt - chính là anh ta.',
    runtime: 105,
    releaseDate: '2024-08-02',
    ageRating: AgeRating.T13,
    director: 'M. Night Shyamalan',
    cast: ['Josh Hartnett', 'Ariel Donoghue', 'Saleka Shyamalan', 'Hayley Mills'],
    genres: ['Giật gân', 'Kinh dị', 'Tội phạm'],
  },
  {
    title: 'Tarot',
    originalTitle: 'Tarot',
    overview: 'Nhóm bạn sử dụng bộ bài tarot bị nguyền và bị giết theo thứ tự lá bài được đọc.',
    runtime: 92,
    releaseDate: '2024-05-03',
    ageRating: AgeRating.T16,
    director: 'Spenser Cohen, Anna Halberg',
    cast: ['Harriet Slater', 'Adain Bradley', 'Avantika Vandanapu', 'Wolfgang Novogratz'],
    genres: ['Kinh dị', 'Siêu nhiên'],
  },
  {
    title: 'The Crow (2024)',
    originalTitle: 'The Crow',
    overview: 'Eric và người yêu bị giết, anh sống lại và có sức mạnh siêu nhiên để trả thù.',
    runtime: 111,
    releaseDate: '2024-08-23',
    ageRating: AgeRating.T18,
    director: 'Rupert Sanders',
    cast: ['Bill Skarsgård', 'FKA Twigs', 'Danny Huston', 'Laura Birn'],
    genres: ['Hành động', 'Kỳ ảo', 'Kinh dị'],
  },

  // === DRAMA/SCI-FI 2018-2025 (15 movies) ===
  {
    title: 'Dune: Part Two - Hành Tinh Cát 2',
    originalTitle: 'Dune: Part Two',
    overview: 'Paul Atreides hợp tác với người Fremen để trả thù những kẻ đã hủy diệt gia đình và khởi đầu cuộc thánh chiến.',
    runtime: 166,
    releaseDate: '2024-03-01',
    ageRating: AgeRating.T13,
    director: 'Denis Villeneuve',
    cast: ['Timothée Chalamet', 'Zendaya', 'Rebecca Ferguson', 'Austin Butler'],
    genres: ['Khoa học viễn tưởng', 'Phiêu lưu', 'Chính kịch'],
  },
  {
    title: 'Inside Out 2 - Những Mảnh Ghép Cảm Xúc 2',
    originalTitle: 'Inside Out 2',
    overview: 'Riley tuổi teen đối mặt với cảm xúc mới: Lo Âu, Ghen Tị, Chán Nản và Xấu Hổ.',
    runtime: 96,
    releaseDate: '2024-06-14',
    ageRating: AgeRating.P,
    director: 'Kelsey Mann',
    cast: ['Amy Poehler', 'Maya Hawke', 'Ayo Edebiri', 'Lewis Black'],
    genres: ['Hoạt hình', 'Gia đình', 'Hài hước'],
  },
  {
    title: 'Despicable Me 4 - Kẻ Trộm Đáng Ghét 4',
    originalTitle: 'Despicable Me 4',
    overview: 'Gru đối mặt với kẻ thù mới và gia đình phải thay đổi danh tính, trong khi các Minion có siêu năng lực.',
    runtime: 94,
    releaseDate: '2024-07-03',
    ageRating: AgeRating.P,
    director: 'Chris Renaud',
    cast: ['Steve Carell', 'Kristen Wiig', 'Will Ferrell', 'Sofia Vergara'],
    genres: ['Hoạt hình', 'Gia đình', 'Hài hước'],
  },
  {
    title: 'Alien: Romulus',
    originalTitle: 'Alien: Romulus',
    overview: 'Nhóm thực dân trẻ khám phá trạm không gian bị bỏ hoang và đối mặt với sinh vật Xenomorph.',
    runtime: 119,
    releaseDate: '2024-08-16',
    ageRating: AgeRating.T18,
    director: 'Fede Álvarez',
    cast: ['Cailee Spaeny', 'David Jonsson', 'Archie Renaux', 'Isabela Merced'],
    genres: ['Kinh dị', 'Khoa học viễn tưởng'],
  },
  {
    title: 'The Wild Robot - Robot Hoang Dã',
    originalTitle: 'The Wild Robot',
    overview: 'Robot hỏng nằm trên đảo hoang và trở thành mẹ nuôi của ngỗng con trong khi học cách sinh tồn.',
    runtime: 101,
    releaseDate: '2024-09-27',
    ageRating: AgeRating.P,
    director: 'Chris Sanders',
    cast: ['Lupita Nyong\'o', 'Pedro Pascal', 'Kit Connor', 'Bill Nighy'],
    genres: ['Hoạt hình', 'Gia đình', 'Khoa học viễn tưởng'],
  },
  {
    title: 'Society of the Snow - Xã Hội Tuyết',
    originalTitle: 'La Sociedad de la Nieve',
    overview: 'Câu chuyện thật về đội bóng rugby Uruguay sống sót 72 ngày trên dãy Andes sau vụ rơi máy bay.',
    runtime: 144,
    releaseDate: '2024-01-04',
    ageRating: AgeRating.T16,
    director: 'J.A. Bayona',
    cast: ['Enzo Vogrincic', 'Matías Recalt', 'Agustín Pardella'],
    genres: ['Chính kịch', 'Sinh tồn', 'Lịch sử'],
  },
  {
    title: 'May December',
    originalTitle: 'May December',
    overview: 'Nữ diễn viên đến gặp người phụ nữ từng có quan hệ scandal với trẻ vị thành niên để nghiên cứu cho vai diễn.',
    runtime: 117,
    releaseDate: '2023-12-01',
    ageRating: AgeRating.T16,
    director: 'Todd Haynes',
    cast: ['Natalie Portman', 'Julianne Moore', 'Charles Melton'],
    genres: ['Chính kịch'],
  },
  {
    title: 'Priscilla',
    originalTitle: 'Priscilla',
    overview: 'Câu chuyện về Priscilla Presley và cuộc hôn nhân với Elvis Presley từ góc nhìn của cô.',
    runtime: 113,
    releaseDate: '2023-11-03',
    ageRating: AgeRating.T16,
    director: 'Sofia Coppola',
    cast: ['Cailee Spaeny', 'Jacob Elordi', 'Ari Cohen', 'Dagmara Dominczyk'],
    genres: ['Tiểu sử', 'Chính kịch', 'Lãng mạn'],
  },
  {
    title: 'Maestro',
    originalTitle: 'Maestro',
    overview: 'Câu chuyện về Leonard Bernstein, nhà soạn nhạc vĩ đại, và mối quan hệ phức tạp với vợ.',
    runtime: 129,
    releaseDate: '2023-12-20',
    ageRating: AgeRating.T16,
    director: 'Bradley Cooper',
    cast: ['Bradley Cooper', 'Carey Mulligan', 'Matt Bomer', 'Maya Hawke'],
    genres: ['Tiểu sử', 'Chính kịch', 'Âm nhạc'],
  },
  {
    title: 'Ferrari',
    originalTitle: 'Ferrari',
    overview: 'Mùa hè 1957, Enzo Ferrari đối mặt với phá sản và đặt cược tất cả vào cuộc đua Mille Miglia.',
    runtime: 130,
    releaseDate: '2023-12-25',
    ageRating: AgeRating.T16,
    director: 'Michael Mann',
    cast: ['Adam Driver', 'Penélope Cruz', 'Shailene Woodley', 'Patrick Dempsey'],
    genres: ['Tiểu sử', 'Chính kịch', 'Thể thao'],
  },
  {
    title: 'American Fiction',
    originalTitle: 'American Fiction',
    overview: 'Tiểu thuyết gia da đen chán ngấy văn chương khai thác chủng tộc viết sách châm biếm và bất ngờ thành công.',
    runtime: 117,
    releaseDate: '2023-12-15',
    ageRating: AgeRating.T16,
    director: 'Cord Jefferson',
    cast: ['Jeffrey Wright', 'Tracee Ellis Ross', 'Issa Rae', 'Sterling K. Brown'],
    genres: ['Hài hước', 'Chính kịch'],
  },
  {
    title: 'The Color Purple (2023)',
    originalTitle: 'The Color Purple',
    overview: 'Celie vượt qua bi kịch và tìm thấy sức mạnh qua tình bạn, tình yêu và âm nhạc.',
    runtime: 141,
    releaseDate: '2023-12-25',
    ageRating: AgeRating.T13,
    director: 'Blitz Bazawule',
    cast: ['Fantasia Barrino', 'Taraji P. Henson', 'Danielle Brooks', 'Colman Domingo'],
    genres: ['Chính kịch', 'Nhạc kịch'],
  },
  {
    title: 'Spaceman - Phi Hành Gia',
    originalTitle: 'Spaceman',
    overview: 'Phi hành gia Czech trong nhiệm vụ đơn độc gặp sinh vật bí ẩn giúp anh đối mặt với hôn nhân đổ vỡ.',
    runtime: 107,
    releaseDate: '2024-03-01',
    ageRating: AgeRating.T16,
    director: 'Johan Renck',
    cast: ['Adam Sandler', 'Carey Mulligan', 'Paul Dano', 'Kunal Nayyar'],
    genres: ['Khoa học viễn tưởng', 'Chính kịch'],
  },
  {
    title: 'Monkey Man',
    originalTitle: 'Monkey Man',
    overview: 'Thanh niên Ấn Độ xâm nhập giới thượng lưu Mumbai để trả thù những kẻ đã hại mẹ.',
    runtime: 121,
    releaseDate: '2024-04-05',
    ageRating: AgeRating.T18,
    director: 'Dev Patel',
    cast: ['Dev Patel', 'Sharlto Copley', 'Sobhita Dhulipala', 'Sikandar Kher'],
    genres: ['Hành động', 'Giật gân'],
  },
  {
    title: 'Kinds of Kindness - Ba Tầng Tàn Nhẫn',
    originalTitle: 'Kinds of Kindness',
    overview: 'Ba câu chuyện riêng biệt về sự kiểm soát, niềm tin và lòng trung thành.',
    runtime: 164,
    releaseDate: '2024-06-21',
    ageRating: AgeRating.T18,
    director: 'Yorgos Lanthimos',
    cast: ['Emma Stone', 'Jesse Plemons', 'Willem Dafoe', 'Margaret Qualley'],
    genres: ['Chính kịch', 'Hài hước đen'],
  },
];

async function main() {
  console.log('🌱 Seeding Movie Service database - BATCH 2 (50 trending 2018-2025)...\n');
  console.log('⚠️ Skipping existing movies by originalTitle...\n');

  const existingGenres = await prisma.genre.findMany();
  const genreMap = new Map(existingGenres.map(g => [g.name, g.id]));

  let successCount = 0;
  let skippedCount = 0;
  let errorCount = 0;

  for (let i = 0; i < movieData.length; i++) {
    const movie = movieData[i];
    try {
      const exists = await prisma.movie.findFirst({
        where: { originalTitle: movie.originalTitle }
      });

      if (exists) {
        skippedCount++;
        console.log(`⏭️  [${i + 1}/${movieData.length}] Skipped (exists): ${movie.title}`);
        continue;
      }

      const createdMovie = await prisma.movie.create({
        data: {
          title: movie.title,
          originalTitle: movie.originalTitle,
          overview: movie.overview,
          posterUrl: `https://via.placeholder.com/500x750?text=${encodeURIComponent(movie.title.slice(0, 20))}`,
          trailerUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
          backdropUrl: `https://via.placeholder.com/1920x1080?text=${encodeURIComponent(movie.title.slice(0, 20))}`,
          runtime: movie.runtime,
          releaseDate: new Date(movie.releaseDate),
          ageRating: movie.ageRating,
          originalLanguage: 'en',
          spokenLanguages: ['vi', 'en'],
          productionCountry: 'Hoa Kỳ',
          languageType: LanguageOption.SUBTITLE,
          director: movie.director,
          cast: movie.cast,
        },
      });

      for (const genreName of movie.genres) {
        const genreId = genreMap.get(genreName);
        if (genreId) {
          await prisma.movieGenre.create({
            data: { movieId: createdMovie.id, genreId },
          });
        }
      }

      successCount++;
      console.log(`✅ [${i + 1}/${movieData.length}] ${movie.title}`);
    } catch (error) {
      errorCount++;
      console.error(`❌ [${i + 1}/${movieData.length}] Failed: ${movie.title}`, error);
    }
  }

  console.log(`\n🎉 Batch 2 complete: ${successCount} created, ${skippedCount} skipped, ${errorCount} failed`);
}

main()
  .catch((e) => {
    console.error('❌ Error seeding database:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
